import { MatchScorecard } from "./types";

export const MATCH_SCORECARDS: Record<string, MatchScorecard> = {
  // ── M1: WESTVILLE VS KEARSNEY (LIVE T20) ──────────────
  m1: {
    matchId: "m1",
    title: "Westville Boys' High 1st XI vs Kearsney College 1st XI",
    venue: "Bowden's Field Oval, Westville",
    date: "2026-03-08",
    format: "T20",
    ageGroup: "1st XI",
    toss: "Kearsney College won the toss and elected to bat first",
    status: "live",
    umpires: ["Shaun George (CSA Panel)", "Bongani Cele (KZNCU)"],
    scorers: ["M. Dube (Official Scorer - WES)", "G. Evans (Official Scorer - KEA)"],
    dlsApplied: false,
    innings1: {
      inningsNumber: 1,
      teamName: "Kearsney College 1st XI",
      teamShort: "KEA",
      totalRuns: 186,
      totalWickets: 5,
      overs: "20.0",
      runRate: 9.30,
      batting: [
        { id: "b1_1", name: "Ross Coetzee", dismissal: "c Whitfield b De Villiers", runs: 68, balls: 41, fours: 7, sixes: 3, sr: 165.85, isNotOut: false, battingPos: 1 },
        { id: "b1_2", name: "Matthew Bergset", dismissal: "b De Villiers", runs: 24, balls: 18, fours: 3, sixes: 0, sr: 133.33, isNotOut: false, battingPos: 2 },
        { id: "b1_3", name: "Hayden Bishop", dismissal: "c Solomons b Govender", runs: 42, balls: 28, fours: 4, sixes: 2, sr: 150.00, isNotOut: false, battingPos: 3 },
        { id: "b1_4", name: "Keegan de Jager", dismissal: "run out (McGough)", runs: 18, balls: 14, fours: 1, sixes: 1, sr: 128.57, isNotOut: false, battingPos: 4 },
        { id: "b1_5", name: "Liam O'Connor", dismissal: "not out", runs: 22, balls: 13, fours: 2, sixes: 1, sr: 169.23, isNotOut: true, battingPos: 5 },
        { id: "b1_6", name: "Dylan Wiggett", dismissal: "c Jansen b McGough", runs: 4, balls: 6, fours: 0, sixes: 0, sr: 66.67, isNotOut: false, battingPos: 6 },
        { id: "b1_7", name: "Siphesihle Zulu", dismissal: "not out", runs: 2, balls: 1, fours: 0, sixes: 0, sr: 200.00, isNotOut: true, battingPos: 7 },
      ],
      didNotBat: ["Cameron Veenstra", "Luke Dudley", "Reece Daniel", "Joshua Stocks"],
      bowling: [
        { id: "bw1_1", name: "Liam De Villiers", overs: "4.0", maidens: 0, runs: 32, wickets: 2, economy: 8.00, dots: 11, fours: 3, sixes: 1, wides: 1, noBalls: 0 },
        { id: "bw1_2", name: "Tristan McGough", overs: "4.0", maidens: 0, runs: 36, wickets: 1, economy: 9.00, dots: 9, fours: 4, sixes: 1, wides: 2, noBalls: 1 },
        { id: "bw1_3", name: "Kyle Govender", overs: "4.0", maidens: 0, runs: 28, wickets: 1, economy: 7.00, dots: 12, fours: 2, sixes: 1, wides: 0, noBalls: 0 },
        { id: "bw1_4", name: "Nathan Jansen", overs: "4.0", maidens: 0, runs: 44, wickets: 0, economy: 11.00, dots: 6, fours: 5, sixes: 2, wides: 2, noBalls: 0 },
        { id: "bw1_5", name: "Ethan Solomons", overs: "4.0", maidens: 0, runs: 40, wickets: 0, economy: 10.00, dots: 7, fours: 3, sixes: 2, wides: 1, noBalls: 0 },
      ],
      extras: { byes: 1, legByes: 2, wides: 6, noBalls: 1, penalties: 0, total: 10 },
      fow: [
        { wicketNumber: 1, score: 54, player: "M. Bergset", over: "5.4" },
        { wicketNumber: 2, score: 118, player: "R. Coetzee", over: "12.3" },
        { wicketNumber: 3, score: 145, player: "K. de Jager", over: "15.5" },
        { wicketNumber: 4, score: 168, player: "H. Bishop", over: "18.1" },
        { wicketNumber: 5, score: 178, player: "D. Wiggett", over: "19.2" },
      ],
      partnerships: [
        { wicket: 1, runs: 54, balls: 34, player1: { name: "R. Coetzee", runs: 32, balls: 19 }, player2: { name: "M. Bergset", runs: 20, balls: 15 } },
        { wicket: 2, runs: 64, balls: 41, player1: { name: "R. Coetzee", runs: 36, balls: 22 }, player2: { name: "H. Bishop", runs: 26, balls: 19 } },
        { wicket: 3, runs: 27, balls: 20, player1: { name: "H. Bishop", runs: 11, balls: 9 }, player2: { name: "K. de Jager", runs: 15, balls: 11 } },
        { wicket: 4, runs: 23, balls: 14, player1: { name: "H. Bishop", runs: 5, balls: 3 }, player2: { name: "L. O'Connor", runs: 16, balls: 11 } },
        { wicket: 5, runs: 10, balls: 7, player1: { name: "L. O'Connor", runs: 4, balls: 2 }, player2: { name: "D. Wiggett", runs: 4, balls: 5 } },
      ],
      phases: {
        powerplay: { name: "Powerplay", oversRange: "1-6", runs: 58, wickets: 1, runRate: 9.67, dots: 16, fours: 7, sixes: 2, dotPct: 44.4, boundaryPct: 25.0, strikeRotPct: 30.6, parScore: 52 },
        middle: { name: "Middle Overs", oversRange: "7-15", runs: 82, wickets: 2, runRate: 9.11, dots: 21, fours: 6, sixes: 3, dotPct: 38.9, boundaryPct: 16.7, strikeRotPct: 44.4, parScore: 78 },
        death: { name: "Death Overs", oversRange: "16-20", runs: 46, wickets: 2, runRate: 9.20, dots: 9, fours: 4, sixes: 2, dotPct: 30.0, boundaryPct: 20.0, strikeRotPct: 50.0, parScore: 48 },
      },
    },
    innings2: {
      inningsNumber: 2,
      teamName: "Westville Boys' High 1st XI",
      teamShort: "WES",
      totalRuns: 142,
      totalWickets: 3,
      overs: "14.2",
      runRate: 9.91,
      batting: [
        { id: "b2_1", name: "James Whitfield", dismissal: "not out", runs: 67, balls: 44, fours: 7, sixes: 2, sr: 152.27, isNotOut: true, battingPos: 1 },
        { id: "b2_2", name: "Nathan Jansen", dismissal: "c Zulu b Bishop", runs: 14, balls: 11, fours: 2, sixes: 0, sr: 127.27, isNotOut: false, battingPos: 2 },
        { id: "b2_3", name: "Chad van Breda", dismissal: "b Coetzee", runs: 22, balls: 16, fours: 3, sixes: 0, sr: 137.50, isNotOut: false, battingPos: 3 },
        { id: "b2_4", name: "Tristan McGough", dismissal: "c Bergset b Zulu", runs: 4, balls: 5, fours: 0, sixes: 0, sr: 80.00, isNotOut: false, battingPos: 4 },
        { id: "b2_5", name: "Ethan Solomons", dismissal: "not out", runs: 31, balls: 29, fours: 3, sixes: 0, sr: 106.90, isNotOut: true, battingPos: 5 },
      ],
      didNotBat: ["Liam De Villiers", "Kyle Govender", "Caleb Thomas", "Matthew Nel", "Keagan Du Plessis", "Reece Pillay"],
      bowling: [
        { id: "bw2_1", name: "Hayden Bishop", overs: "3.0", maidens: 0, runs: 26, wickets: 1, economy: 8.67, dots: 8, fours: 3, sixes: 0, wides: 1, noBalls: 0 },
        { id: "bw2_2", name: "Ross Coetzee", overs: "3.0", maidens: 0, runs: 29, wickets: 1, economy: 9.67, dots: 6, fours: 2, sixes: 1, wides: 1, noBalls: 0 },
        { id: "bw2_3", name: "Siphesihle Zulu", overs: "3.0", maidens: 0, runs: 24, wickets: 1, economy: 8.00, dots: 7, fours: 2, sixes: 0, wides: 0, noBalls: 0 },
        { id: "bw2_4", name: "T. Ndlovu", overs: "3.2", maidens: 0, runs: 34, wickets: 0, economy: 10.20, dots: 7, fours: 4, sixes: 1, wides: 2, noBalls: 0 },
        { id: "bw2_5", name: "Cameron Veenstra", overs: "2.0", maidens: 0, runs: 25, wickets: 0, economy: 12.50, dots: 3, fours: 3, sixes: 0, wides: 0, noBalls: 0 },
      ],
      extras: { byes: 0, legByes: 1, wides: 3, noBalls: 0, penalties: 0, total: 4 },
      fow: [
        { wicketNumber: 1, score: 28, player: "N. Jansen", over: "3.1" },
        { wicketNumber: 2, score: 68, player: "C. van Breda", over: "7.2" },
        { wicketNumber: 3, score: 78, player: "T. McGough", over: "8.5" },
      ],
      partnerships: [
        { wicket: 1, runs: 28, balls: 19, player1: { name: "J. Whitfield", runs: 14, balls: 9 }, player2: { name: "N. Jansen", runs: 14, balls: 10 } },
        { wicket: 2, runs: 40, balls: 25, player1: { name: "J. Whitfield", runs: 18, balls: 12 }, player2: { name: "C. van Breda", runs: 22, balls: 13 } },
        { wicket: 3, runs: 10, balls: 9, player1: { name: "J. Whitfield", runs: 6, balls: 4 }, player2: { name: "T. McGough", runs: 4, balls: 5 } },
        { wicket: 4, runs: 64, balls: 47, player1: { name: "J. Whitfield", runs: 29, balls: 19 }, player2: { name: "E. Solomons", runs: 31, balls: 28 }, unbroken: true },
      ],
      phases: {
        powerplay: { name: "Powerplay", oversRange: "1-6", runs: 56, wickets: 1, runRate: 9.33, dots: 17, fours: 6, sixes: 1, dotPct: 47.2, boundaryPct: 19.4, strikeRotPct: 33.3, parScore: 54 },
        middle: { name: "Middle Overs", oversRange: "7-15", runs: 86, wickets: 2, runRate: 10.32, dots: 18, fours: 8, sixes: 1, dotPct: 36.0, boundaryPct: 18.0, strikeRotPct: 46.0, parScore: 76 },
        death: { name: "Death Overs", oversRange: "16-20", runs: 0, wickets: 0, runRate: 0.00, dots: 0, fours: 0, sixes: 0, dotPct: 0, boundaryPct: 0, strikeRotPct: 0, parScore: 45 },
      },
    },
    manhattan: [
      { over: 1, runs: 8, wickets: 0, bowler: "H. Bishop", phase: "powerplay", totalSoFar: 8 },
      { over: 2, runs: 11, wickets: 0, bowler: "R. Coetzee", phase: "powerplay", totalSoFar: 19 },
      { over: 3, runs: 9, wickets: 0, bowler: "H. Bishop", phase: "powerplay", totalSoFar: 28 },
      { over: 4, runs: 7, wickets: 1, bowler: "S. Zulu", phase: "powerplay", totalSoFar: 35 },
      { over: 5, runs: 12, wickets: 0, bowler: "R. Coetzee", phase: "powerplay", totalSoFar: 47 },
      { over: 6, runs: 9, wickets: 0, bowler: "S. Zulu", phase: "powerplay", totalSoFar: 56 },
      { over: 7, runs: 11, wickets: 0, bowler: "T. Ndlovu", phase: "middle", totalSoFar: 67 },
      { over: 8, runs: 5, wickets: 1, bowler: "R. Coetzee", phase: "middle", totalSoFar: 72 },
      { over: 9, runs: 8, wickets: 1, bowler: "S. Zulu", phase: "middle", totalSoFar: 80 },
      { over: 10, runs: 14, wickets: 0, bowler: "T. Ndlovu", phase: "middle", totalSoFar: 94 },
      { over: 11, runs: 12, wickets: 0, bowler: "C. Veenstra", phase: "middle", totalSoFar: 106 },
      { over: 12, runs: 10, wickets: 0, bowler: "H. Bishop", phase: "middle", totalSoFar: 116 },
      { over: 13, runs: 13, wickets: 0, bowler: "C. Veenstra", phase: "middle", totalSoFar: 129 },
      { over: 14, runs: 12, wickets: 0, bowler: "T. Ndlovu", phase: "middle", totalSoFar: 141 },
      { over: 15, runs: 1, wickets: 0, bowler: "T. Ndlovu", phase: "middle", totalSoFar: 142 },
    ],
    worm: [
      { over: 0, team1Runs: 0, team2Runs: 0, targetLine: 0 },
      { over: 2, team1Runs: 16, team2Runs: 19, targetLine: 18 },
      { over: 4, team1Runs: 38, team2Runs: 35, targetLine: 37 },
      { over: 6, team1Runs: 58, team2Runs: 56, targetLine: 56 },
      { over: 8, team1Runs: 79, team2Runs: 72, targetLine: 75 },
      { over: 10, team1Runs: 98, team2Runs: 94, targetLine: 94 },
      { over: 12, team1Runs: 114, team2Runs: 116, targetLine: 112 },
      { over: 14, team1Runs: 134, team2Runs: 141, targetLine: 131 },
      { over: 16, team1Runs: 152, targetLine: 150 },
      { over: 18, team1Runs: 168, targetLine: 168 },
      { over: 20, team1Runs: 186, targetLine: 187 },
    ],
    winProb: {
      teamA: 68,
      teamB: 32,
      teamAName: "Westville",
      teamBName: "Kearsney",
      momentumText: "Westville require 45 runs from 34 balls with 7 wickets in hand (Req. RR: 7.94). Win predictor favours Westville at 68%.",
    },
  },

  // ── M2: HILTON VS MICHAELHOUSE (LIVE DECLARATION / MULTI-DAY) ──
  m2: {
    matchId: "m2",
    title: "Hilton College 1st XI vs Michaelhouse 1st XI",
    venue: "Weightman-Smith Oval, Hilton",
    date: "2026-03-08",
    format: "Declaration",
    ageGroup: "1st XI",
    toss: "Hilton College won the toss and elected to bat first",
    status: "live",
    umpires: ["Adrian Holdstock (ICC Elite)", "Deon van Wyk (KZNCU)"],
    scorers: ["K. Sithole (Hilton)", "B. Khanyile (Michaelhouse)"],
    innings1: {
      inningsNumber: 1,
      teamName: "Hilton College 1st XI",
      teamShort: "HIL",
      totalRuns: 214,
      totalWickets: 4,
      overs: "48.1",
      runRate: 4.44,
      batting: [
        { id: "h1_1", name: "Matthew Stewart", dismissal: "not out", runs: 104, balls: 132, fours: 12, sixes: 3, sr: 78.79, isNotOut: true, battingPos: 1 },
        { id: "h1_2", name: "Charles Swart", dismissal: "c Higgs b Baker", runs: 19, balls: 36, fours: 2, sixes: 0, sr: 52.78, isNotOut: false, battingPos: 2 },
        { id: "h1_3", name: "Ben Hockly", dismissal: "b Higgs", runs: 28, balls: 44, fours: 4, sixes: 0, sr: 63.64, isNotOut: false, battingPos: 3 },
        { id: "h1_4", name: "Kyle Christie", dismissal: "lbw b Gaskin", runs: 9, balls: 17, fours: 1, sixes: 0, sr: 52.94, isNotOut: false, battingPos: 4 },
        { id: "h1_5", name: "Luke Campbell", dismissal: "not out", runs: 48, balls: 61, fours: 4, sixes: 0, sr: 78.69, isNotOut: true, battingPos: 5 },
      ],
      didNotBat: ["Alex Pitman", "David Tatham", "Nathaniel Berlyn", "Jack Campbell", "Liam Armstrong", "Reece Thomas"],
      bowling: [
        { id: "mhb_1", name: "Hayden Higgs", overs: "14.0", maidens: 3, runs: 48, wickets: 1, economy: 3.43, dots: 56, fours: 5, sixes: 0, wides: 1, noBalls: 0 },
        { id: "mhb_2", name: "Murray Baker", overs: "12.0", maidens: 2, runs: 44, wickets: 1, economy: 3.67, dots: 46, fours: 4, sixes: 1, wides: 2, noBalls: 0 },
        { id: "mhb_3", name: "Luke Gaskin", overs: "11.1", maidens: 1, runs: 58, wickets: 1, economy: 5.19, dots: 38, fours: 7, sixes: 1, wides: 0, noBalls: 1 },
        { id: "mhb_4", name: "C. Muirhead", overs: "8.0", maidens: 0, runs: 46, wickets: 0, economy: 5.75, dots: 24, fours: 5, sixes: 1, wides: 1, noBalls: 0 },
        { id: "mhb_5", name: "T. Bailey", overs: "3.0", maidens: 0, runs: 16, wickets: 0, economy: 5.33, dots: 10, fours: 2, sixes: 0, wides: 0, noBalls: 0 },
      ],
      extras: { byes: 2, legByes: 1, wides: 2, noBalls: 1, penalties: 0, total: 6 },
      fow: [
        { wicketNumber: 1, score: 38, player: "C. Swart", over: "11.2" },
        { wicketNumber: 2, score: 98, player: "B. Hockly", over: "24.5" },
        { wicketNumber: 3, score: 114, player: "K. Christie", over: "29.1" },
      ],
      partnerships: [
        { wicket: 1, runs: 38, balls: 68, player1: { name: "M. Stewart", runs: 18, balls: 32 }, player2: { name: "C. Swart", runs: 19, balls: 36 } },
        { wicket: 2, runs: 60, balls: 81, player1: { name: "M. Stewart", runs: 32, balls: 37 }, player2: { name: "B. Hockly", runs: 28, balls: 44 } },
        { wicket: 3, runs: 16, balls: 26, player1: { name: "M. Stewart", runs: 7, balls: 9 }, player2: { name: "K. Christie", runs: 9, balls: 17 } },
        { wicket: 4, runs: 100, balls: 114, player1: { name: "M. Stewart", runs: 47, balls: 54 }, player2: { name: "L. Campbell", runs: 48, balls: 61 }, unbroken: true },
      ],
      phases: {
        powerplay: { name: "Powerplay", oversRange: "1-10", runs: 34, wickets: 0, runRate: 3.40, dots: 42, fours: 4, sixes: 0, dotPct: 70.0, boundaryPct: 6.7, strikeRotPct: 23.3, parScore: 40 },
        middle: { name: "Middle Overs", oversRange: "11-35", runs: 106, wickets: 3, runRate: 4.24, dots: 92, fours: 12, sixes: 1, dotPct: 61.3, boundaryPct: 8.7, strikeRotPct: 30.0, parScore: 95 },
        death: { name: "Death Overs", oversRange: "36-48", runs: 74, wickets: 0, runRate: 5.69, dots: 38, fours: 7, sixes: 2, dotPct: 48.7, boundaryPct: 11.5, strikeRotPct: 39.8, parScore: 65 },
      },
    },
    manhattan: [
      { over: 5, runs: 16, wickets: 0, bowler: "H. Higgs", phase: "powerplay", totalSoFar: 16 },
      { over: 10, runs: 18, wickets: 0, bowler: "M. Baker", phase: "powerplay", totalSoFar: 34 },
      { over: 15, runs: 22, wickets: 1, bowler: "L. Gaskin", phase: "middle", totalSoFar: 56 },
      { over: 20, runs: 19, wickets: 0, bowler: "H. Higgs", phase: "middle", totalSoFar: 75 },
      { over: 25, runs: 25, wickets: 1, bowler: "M. Baker", phase: "middle", totalSoFar: 100 },
      { over: 30, runs: 18, wickets: 1, bowler: "L. Gaskin", phase: "middle", totalSoFar: 118 },
      { over: 35, runs: 22, wickets: 0, bowler: "C. Muirhead", phase: "middle", totalSoFar: 140 },
      { over: 40, runs: 28, wickets: 0, bowler: "H. Higgs", phase: "death", totalSoFar: 168 },
      { over: 45, runs: 32, wickets: 0, bowler: "L. Gaskin", phase: "death", totalSoFar: 200 },
      { over: 48, runs: 14, wickets: 0, bowler: "M. Baker", phase: "death", totalSoFar: 214 },
    ],
    worm: [
      { over: 0, team1Runs: 0 },
      { over: 10, team1Runs: 34 },
      { over: 20, team1Runs: 75 },
      { over: 30, team1Runs: 118 },
      { over: 40, team1Runs: 168 },
      { over: 48, team1Runs: 214 },
    ],
    winProb: {
      teamA: 55,
      teamB: 15,
      teamAName: "Hilton",
      teamBName: "Michaelhouse",
      momentumText: "Hilton are in commanding position at 214/4. Draw probability at 30%.",
    },
  },

  // ── M5: MICHAELHOUSE VS ST CHARLES (COMPLETED 50-OVER MATCH) ──
  m5: {
    matchId: "m5",
    title: "Michaelhouse 1st XI vs St Charles College 1st XI",
    venue: "Roy Gathorne Oval, Balgowan",
    date: "2026-02-28",
    format: "50-Over",
    ageGroup: "1st XI",
    toss: "St Charles College won the toss and elected to bat first",
    status: "complete",
    result: "Michaelhouse 1st XI won by 5 wickets",
    playerOfMatch: "Hayden Higgs (MHS) - 4/31 (9.2 ov) & 62* (54b)",
    umpires: ["Clive Jacobs", "Bongani Cele"],
    scorers: ["M. Ndaba (MHS)", "P. Van Zyl (SCC)"],
    innings1: {
      inningsNumber: 1,
      teamName: "St Charles College 1st XI",
      teamShort: "SCC",
      totalRuns: 198,
      totalWickets: 10,
      overs: "44.2",
      runRate: 4.47,
      batting: [
        { id: "sc_1", name: "Cian Fortmann", dismissal: "c Baker b Higgs", runs: 44, balls: 58, fours: 5, sixes: 1, sr: 75.86, isNotOut: false, battingPos: 1 },
        { id: "sc_2", name: "Brendon Sunguro", dismissal: "b Gaskin", runs: 12, balls: 22, fours: 1, sixes: 0, sr: 54.55, isNotOut: false, battingPos: 2 },
        { id: "sc_3", name: "Rico Honiball", dismissal: "c Higgs b Muirhead", runs: 58, balls: 72, fours: 7, sixes: 1, sr: 80.56, isNotOut: false, battingPos: 3 },
        { id: "sc_4", name: "Marcel Wellmann", dismissal: "lbw b Higgs", runs: 26, balls: 38, fours: 2, sixes: 0, sr: 68.42, isNotOut: false, battingPos: 4 },
        { id: "sc_5", name: "Kwando Ndlovu", dismissal: "c Gaskin b Higgs", runs: 8, balls: 14, fours: 1, sixes: 0, sr: 57.14, isNotOut: false, battingPos: 5 },
        { id: "sc_6", name: "Tristan Montile", dismissal: "b Higgs", runs: 0, balls: 2, fours: 0, sixes: 0, sr: 0.00, isNotOut: false, battingPos: 6 },
        { id: "sc_7", name: "Connor Simpson", dismissal: "run out (Higgs)", runs: 18, balls: 29, fours: 1, sixes: 0, sr: 62.07, isNotOut: false, battingPos: 7 },
        { id: "sc_8", name: "Rowan Rajah", dismissal: "c Baker b Gaskin", runs: 11, balls: 16, fours: 1, sixes: 0, sr: 68.75, isNotOut: false, battingPos: 8 },
        { id: "sc_9", name: "Lwandle Mhlungu", dismissal: "c Muirhead b Baker", runs: 4, balls: 9, fours: 0, sixes: 0, sr: 44.44, isNotOut: false, battingPos: 9 },
        { id: "sc_10", name: "Matthew Urquhart", dismissal: "b Baker", runs: 2, balls: 5, fours: 0, sixes: 0, sr: 40.00, isNotOut: false, battingPos: 10 },
        { id: "sc_11", name: "Dean Moodley", dismissal: "not out", runs: 1, balls: 1, fours: 0, sixes: 0, sr: 100.00, isNotOut: true, battingPos: 11 },
      ],
      didNotBat: [],
      bowling: [
        { id: "mhb_bw1", name: "Hayden Higgs", overs: "9.2", maidens: 2, runs: 31, wickets: 4, economy: 3.32, dots: 42, fours: 3, sixes: 0, wides: 1, noBalls: 0 },
        { id: "mhb_bw2", name: "Luke Gaskin", overs: "10.0", maidens: 1, runs: 42, wickets: 2, economy: 4.20, dots: 38, fours: 4, sixes: 1, wides: 2, noBalls: 0 },
        { id: "mhb_bw3", name: "Murray Baker", overs: "9.0", maidens: 0, runs: 38, wickets: 2, economy: 4.22, dots: 32, fours: 4, sixes: 0, wides: 1, noBalls: 0 },
        { id: "mhb_bw4", name: "C. Muirhead", overs: "10.0", maidens: 0, runs: 48, wickets: 1, economy: 4.80, dots: 34, fours: 5, sixes: 1, wides: 0, noBalls: 0 },
        { id: "mhb_bw5", name: "T. Bailey", overs: "6.0", maidens: 0, runs: 31, wickets: 0, economy: 5.17, dots: 18, fours: 2, sixes: 1, wides: 2, noBalls: 0 },
      ],
      extras: { byes: 3, legByes: 2, wides: 8, noBalls: 1, penalties: 0, total: 14 },
      fow: [
        { wicketNumber: 1, score: 28, player: "B. Sunguro", over: "6.4" },
        { wicketNumber: 2, score: 86, player: "C. Fortmann", over: "18.2" },
        { wicketNumber: 3, score: 142, player: "M. Wellmann", over: "29.4" },
        { wicketNumber: 4, score: 156, player: "R. Honiball", over: "33.1" },
        { wicketNumber: 5, score: 156, player: "T. Montile", over: "33.3" },
        { wicketNumber: 6, score: 168, player: "K. Ndlovu", over: "36.2" },
        { wicketNumber: 7, score: 189, player: "R. Rajah", over: "41.1" },
        { wicketNumber: 8, score: 194, player: "C. Simpson", over: "42.5" },
        { wicketNumber: 9, score: 197, player: "L. Mhlungu", over: "43.4" },
        { wicketNumber: 10, score: 198, player: "M. Urquhart", over: "44.2" },
      ],
      partnerships: [
        { wicket: 1, runs: 28, balls: 40, player1: { name: "C. Fortmann", runs: 16, balls: 18 }, player2: { name: "B. Sunguro", runs: 12, balls: 22 } },
        { wicket: 2, runs: 58, balls: 70, player1: { name: "C. Fortmann", runs: 28, balls: 40 }, player2: { name: "R. Honiball", runs: 30, balls: 30 } },
        { wicket: 3, runs: 56, balls: 68, player1: { name: "R. Honiball", runs: 28, balls: 38 }, player2: { name: "M. Wellmann", runs: 26, balls: 30 } },
      ],
      phases: {
        powerplay: { name: "Powerplay", oversRange: "1-10", runs: 48, wickets: 1, runRate: 4.80, dots: 44, fours: 5, sixes: 0, dotPct: 73.3, boundaryPct: 8.3, strikeRotPct: 18.3, parScore: 45 },
        middle: { name: "Middle Overs", oversRange: "11-40", runs: 128, wickets: 5, runRate: 4.27, dots: 104, fours: 12, sixes: 2, dotPct: 57.8, boundaryPct: 7.8, strikeRotPct: 34.4, parScore: 130 },
        death: { name: "Death Overs", oversRange: "41-50", runs: 22, wickets: 4, runRate: 5.08, dots: 16, fours: 2, sixes: 1, dotPct: 61.5, boundaryPct: 11.5, strikeRotPct: 26.9, parScore: 40 },
      },
    },
    innings2: {
      inningsNumber: 2,
      teamName: "Michaelhouse 1st XI",
      teamShort: "MHS",
      totalRuns: 201,
      totalWickets: 5,
      overs: "41.1",
      runRate: 4.88,
      batting: [
        { id: "mhs_1", name: "Murray Baker", dismissal: "c Sunguro b Urquhart", runs: 33, balls: 40, fours: 4, sixes: 1, sr: 82.50, isNotOut: false, battingPos: 1 },
        { id: "mhs_2", name: "Luke Gaskin", dismissal: "b Mhlungu", runs: 24, balls: 36, fours: 3, sixes: 0, sr: 66.67, isNotOut: false, battingPos: 2 },
        { id: "mhs_3", name: "Hayden Higgs", dismissal: "not out", runs: 62, balls: 54, fours: 6, sixes: 2, sr: 114.81, isNotOut: true, battingPos: 3 },
        { id: "mhs_4", name: "C. Muirhead", dismissal: "c Fortmann b Urquhart", runs: 18, balls: 24, fours: 2, sixes: 0, sr: 75.00, isNotOut: false, battingPos: 4 },
        { id: "mhs_5", name: "T. Bailey", dismissal: "lbw b Rajah", runs: 14, balls: 22, fours: 1, sixes: 0, sr: 63.64, isNotOut: false, battingPos: 5 },
        { id: "mhs_6", name: "R. Brown", dismissal: "c Wellmann b Urquhart", runs: 12, balls: 19, fours: 1, sixes: 0, sr: 63.16, isNotOut: false, battingPos: 6 },
        { id: "mhs_7", name: "S. Khumalo", dismissal: "not out", runs: 26, balls: 28, fours: 3, sixes: 0, sr: 92.86, isNotOut: true, battingPos: 7 },
      ],
      didNotBat: ["D. Smith", "A. Ndlovu", "J. Van Rooyen", "L. Botha"],
      bowling: [
        { id: "sc_bw1", name: "Matthew Urquhart", overs: "9.0", maidens: 1, runs: 44, wickets: 3, economy: 4.89, dots: 34, fours: 5, sixes: 1, wides: 1, noBalls: 0 },
        { id: "sc_bw2", name: "Lwandle Mhlungu", overs: "8.0", maidens: 0, runs: 39, wickets: 1, economy: 4.88, dots: 28, fours: 4, sixes: 0, wides: 2, noBalls: 0 },
        { id: "sc_bw3", name: "Rowan Rajah", overs: "10.0", maidens: 1, runs: 45, wickets: 1, economy: 4.50, dots: 36, fours: 3, sixes: 1, wides: 1, noBalls: 0 },
        { id: "sc_bw4", name: "Connor Simpson", overs: "7.1", maidens: 0, runs: 41, wickets: 0, economy: 5.72, dots: 20, fours: 4, sixes: 1, wides: 3, noBalls: 0 },
        { id: "sc_bw5", name: "Brendon Sunguro", overs: "7.0", maidens: 0, runs: 28, wickets: 0, economy: 4.00, dots: 26, fours: 2, sixes: 0, wides: 0, noBalls: 0 },
      ],
      extras: { byes: 1, legByes: 3, wides: 7, noBalls: 1, penalties: 0, total: 12 },
      fow: [
        { wicketNumber: 1, score: 48, player: "L. Gaskin", over: "10.2" },
        { wicketNumber: 2, score: 72, player: "M. Baker", over: "15.1" },
        { wicketNumber: 3, score: 104, player: "C. Muirhead", over: "22.3" },
        { wicketNumber: 4, score: 132, player: "T. Bailey", over: "28.5" },
        { wicketNumber: 5, score: 154, player: "R. Brown", over: "33.2" },
      ],
      partnerships: [
        { wicket: 1, runs: 48, balls: 62, player1: { name: "M. Baker", runs: 22, balls: 26 }, player2: { name: "L. Gaskin", runs: 24, balls: 36 } },
        { wicket: 2, runs: 24, balls: 29, player1: { name: "M. Baker", runs: 11, balls: 14 }, player2: { name: "H. Higgs", runs: 13, balls: 15 } },
        { wicket: 3, runs: 32, balls: 44, player1: { name: "H. Higgs", runs: 14, balls: 20 }, player2: { name: "C. Muirhead", runs: 18, balls: 24 } },
        { wicket: 4, runs: 28, balls: 38, player1: { name: "H. Higgs", runs: 14, balls: 16 }, player2: { name: "T. Bailey", runs: 14, balls: 22 } },
        { wicket: 5, runs: 22, balls: 27, player1: { name: "H. Higgs", runs: 10, balls: 8 }, player2: { name: "R. Brown", runs: 12, balls: 19 } },
        { wicket: 6, runs: 47, balls: 47, player1: { name: "H. Higgs", runs: 21, balls: 19 }, player2: { name: "S. Khumalo", runs: 26, balls: 28 }, unbroken: true },
      ],
      phases: {
        powerplay: { name: "Powerplay", oversRange: "1-10", runs: 46, wickets: 0, runRate: 4.60, dots: 42, fours: 5, sixes: 0, dotPct: 70.0, boundaryPct: 8.3, strikeRotPct: 21.7, parScore: 45 },
        middle: { name: "Middle Overs", oversRange: "11-40", runs: 148, wickets: 5, runRate: 4.93, dots: 98, fours: 14, sixes: 3, dotPct: 54.4, boundaryPct: 9.4, strikeRotPct: 36.1, parScore: 135 },
        death: { name: "Death Overs", oversRange: "41-50", runs: 7, wickets: 0, runRate: 6.00, dots: 4, fours: 1, sixes: 0, dotPct: 57.1, boundaryPct: 14.3, strikeRotPct: 28.6, parScore: 20 },
      },
    },
    manhattan: [
      { over: 5, runs: 22, wickets: 0, bowler: "M. Urquhart", phase: "powerplay", totalSoFar: 22 },
      { over: 10, runs: 24, wickets: 0, bowler: "L. Mhlungu", phase: "powerplay", totalSoFar: 46 },
      { over: 15, runs: 26, wickets: 2, bowler: "R. Rajah", phase: "middle", totalSoFar: 72 },
      { over: 20, runs: 22, wickets: 0, bowler: "C. Simpson", phase: "middle", totalSoFar: 94 },
      { over: 25, runs: 24, wickets: 1, bowler: "M. Urquhart", phase: "middle", totalSoFar: 118 },
      { over: 30, runs: 20, wickets: 1, bowler: "R. Rajah", phase: "middle", totalSoFar: 138 },
      { over: 35, runs: 28, wickets: 1, bowler: "M. Urquhart", phase: "middle", totalSoFar: 166 },
      { over: 40, runs: 28, wickets: 0, bowler: "C. Simpson", phase: "middle", totalSoFar: 194 },
      { over: 41, runs: 7, wickets: 0, bowler: "B. Sunguro", phase: "death", totalSoFar: 201 },
    ],
    worm: [
      { over: 0, team1Runs: 0, team2Runs: 0 },
      { over: 10, team1Runs: 48, team2Runs: 46 },
      { over: 20, team1Runs: 94, team2Runs: 94 },
      { over: 30, team1Runs: 144, team2Runs: 138 },
      { over: 40, team1Runs: 182, team2Runs: 194 },
      { over: 44, team1Runs: 198, team2Runs: 201 },
    ],
    winProb: {
      teamA: 0,
      teamB: 100,
      teamAName: "St Charles",
      teamBName: "Michaelhouse",
      momentumText: "Match Concluded: Michaelhouse won by 5 wickets with 53 balls remaining.",
    },
  },
};
